sudo: required

os:
  - linux

services:
  - docker

before_install:
  - docker pull donghokang/raigraphics:latest
  - docker run -itd -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR --name raigraphics-docker donghokang/raigraphics:latest

script:
  - docker exec raigraphics-docker /bin/bash -c "cd $TRAVIS_BUILD_DIR && ./.ci/build.sh"

notifications:
  slack: rai-dev:NQfHVfMfVUCpU9IeC7ESuDtW